### ISSUE TITLE
include <numpy/arrayobject.h> not needed

### ISSUE THREAD

**Issue by piyushrpt** [leiyangleon/autoRIFT#10]
I don't think this header file is needed for autorift. It is included but never used. 
Will keep the compile line shorter and easier to integrate with other tools.

**Comment by piyushrpt** [comment]
@rtburns-jpl - FYI

**Comment by leiyangleon** [comment]
> I don't think this header file is needed for autorift. It is included but never used.
> Will keep the compile line shorter and easier to integrate with other tools.

I remember it was used; otherwise, compiling would fail, which is why I added it. I just checked the code, see the [declaration](https://github.com/leiyangleon/autoRIFT/blob/b91cef424f2a36534993f6bbddeea59822afbc44/geo_autoRIFT/autoRIFT/bindings/autoriftcoremodule.cpp#L112) of PyArrayObject in sub-function `arPixDisp_u`. There are another three similar uses in the c++ binding file `autoriftcoremodule.cpp` .

**Comment by piyushrpt** [comment]
Got it. My bad. Yep - it is needed.
